### ISSUE TITLE
Index out of bounds exception.

### ISSUE THREAD

**Issue by mackaiver** [fact-project/smart_fact_crawler#6]
So this happened:

```
00:27:28 - ERROR - shift_helper.Check | list index out of range
Traceback (most recent call last):
  File "/Users/Kai/anaconda3/envs/shift/lib/python3.5/site-packages/shifthelper/checks/__init__.py", line 51, in run
    self.check()
  File "/Users/Kai/anaconda3/envs/shift/lib/python3.5/site-packages/shifthelper/checks/webdim.py", line 11, in check
    s = smart_fact_crawler.status()
  File "/Users/Kai/anaconda3/envs/shift/lib/python3.5/site-packages/smart_fact_crawler/__init__.py", line 182, in status
    'Time_Stamp': smartfact_time2datetime(tc[0, 0]),
  File "/Users/Kai/anaconda3/envs/shift/lib/python3.5/site-packages/smart_fact_crawler/__init__.py", line 23, in __getitem__
    item = self.page_payload[row].split()[col]
IndexError: list index out of range
```

**Comment by dneise** [comment]
Did it happen often or once per night?
If it was often, can you post the shifthelper logfile here?

**Comment by mackaiver** [comment]
It happend just once.

[shifthelper_2016-09-10.txt](https://github.com/fact-project/smart_fact_crawler/files/465793/shifthelper_2016-09-10.txt)
